# Generated by Django 4.1.4 on 2022-12-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='max_size',
            new_name='size_used',
        ),
    ]
