# Generated by Django 4.1.4 on 2022-12-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
