# Generated by Django 4.1.4 on 2022-12-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_postmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='content',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
